module

import Lean
public import Lean.Elab.Term.TermElabM
public import Lean.Meta.Tactic.Simp.SimpTheorems

open Lean Meta Expr Name Elab Tactic Std DiscrTree Trie Key

namespace Canonical

public section

def UNFOLD_HARD_CODE : NameSet := .ofList [
  `Set.instMembership, `Set.Mem, `setOf, `instLENat
]

/-- The arity of a function symbol and the arity of its parameters, recursively. -/
structure Arity where
  params : Array Arity := #[]
deriving Inhabited

/-- The `Arity` of a type `e`.
    Should be performed in `withArityUnfold` for consistent results. -/
partial def typeArity (e : Expr) : MetaM Arity := do
  forallTelescopeReducing e fun xs _ => do
    pure ⟨← xs.mapM fun param => do
      let id := param.fvarId!
      pure (← typeArity (← id.getType))⟩

/-- The number of parameters in type `e`. -/
partial def typeArity1 (e : Expr) : MetaM Nat := do
  forallTelescopeReducing e fun xs _ => return xs.size

/-- Given a head symbol `Expr`, returns a `Name` for serializing and its type. -/
def toHead : Expr → MetaM (Name × Expr)
| .fvar id =>
  return (id.name.updatePrefix (← id.getUserName).getRoot, ← id.getType)
| .mvar id =>
  return (((← getMCtx).getDecl id).userName, ← id.getType)
| .sort l =>
  return (`Sort, .sort (l.succ))
| .const name us =>
  return (name, (← getConstInfo name).instantiateTypeLevelParams us)
| .lit l =>
  let name : Name := match l with
  | .natVal n => .num .anonymous n
  | .strVal s => .str .anonymous s!"\"{s}\""
  return (name, l.type)
| e => do panic! s!"toHead called with on {← Meta.ppExpr e}"

def toNameString (e : Expr) : MetaM String := return (← toHead e).1.toString

/-- Determines whether something of type `e` can accept an argument.
    Should be performed in `withArityUnfold` for consistent results. -/
partial def hidesForall (e : Expr) : MetaM Bool := do
  match ← whnf e with
  | .lam name type body info =>
    withLocalDecl name info type fun fvar => hidesForall (body.instantiate1 fvar)
  | .forallE _ _ _ _ => pure true
  | _ => pure false

/-- `canUnfold` predicate for `withArityUnfold`, unfolding constants that hide a `forallE`. -/
def canUnfold (monomorphize : Bool) (cfg : Config) (info : ConstantInfo) : CoreM Bool := do
  match cfg.transparency with
  | .all => return true
  | .default => return !(← isIrreducible info.name)
  | m =>
    let env ← getEnv
    if (← isReducible info.name) || (UNFOLD_HARD_CODE.contains info.name)
      || (Compiler.getInlineAttribute? env info.name matches .some .inline) then
      return true
    -- If `monomorphize`, we only reduce `OfNat` instances.
    else if m == .instances && (← isInstance info.name) &&
      (!monomorphize || (← (isClass? (info.type)).run' {}) == some `OfNat || info.name.getPrefix == `Set) then
      return true
    else if let some value := info.value? then
      return ← (hidesForall value).run' {}
    else return false

/-- Whether `e` contains a recursor or auxiliary recursor. -/
def isRecursive (e : Expr) : MetaM Bool := do
  let env ← getEnv
  return e.getUsedConstants.any fun c =>
    (env.find? c).get! matches .recInfo _ || isAuxRecursor env c

/-- A natural number as expressed as an application of constructors. -/
def rawRawNatLit : Nat → Expr
| 0 => .const ``Nat.zero []
| n + 1 => .app (.const ``Nat.succ []) (rawRawNatLit n)

variable [MonadControlT MetaM n] [Monad n]

/-- Guarantees consistent (static) arity. -/
@[inline] def withArityUnfold (monomorphize : Bool) (e : n α) : n α :=
  withReducibleAndInstances (withCanUnfoldPred (canUnfold monomorphize) e)

def withNoUnfoldPred [MonadControlT MetaM m] [Monad m] : m α → m α :=
  mapMetaM <| withReader (fun ctx => { ctx with canUnfold? := none })

def withoutArityUnfold [MonadControlT MetaM m] [Monad m] (x : m α) : m α :=
  withDefault do withNoUnfoldPred do x

/-- `dbg_trace` is not visible in the event of a crash or infinite loop. -/
def printForce (s : String) : IO Unit := do
  let handle ← IO.FS.Handle.mk "output.txt" IO.FS.Mode.append
  handle.putStrLn s
  handle.flush

/-- Pretty printing options for proofs generated by Canonical. -/
def applyOptions (opts : Options) : Options := opts |>
  (pp.proofs.set · true) |>
  (pp.motives.all.set · true) |>
  (pp.unicode.fun.set · true) |>
  (pp.letVarTypes.set · true)

/-- `instantiateLambda` but simpler, and outside `MetaM`. -/
def apply (e : Expr) (args : List Expr) : Expr :=
  match args with
  | [] => e
  | arg :: args => match e with
    | .lam _name _type body _info =>
      apply (body.instantiate1 arg) args
    | _ => panic! "apply: expected a lambda, got {e}"

/-- Like `lambdaMetaTelescope`, but with user-selected `MetavarKind`. -/
partial def lambdaMetaTelescope' (e : Expr) (maxMVars? : Option Nat := none) (kind : MetavarKind := .natural) : MetaM (Array Expr × Array BinderInfo × Expr) :=
  process #[] #[] 0 e
where
  process (mvars : Array Expr) (bis : Array BinderInfo) (j : Nat) (type : Expr) : MetaM (Array Expr × Array BinderInfo × Expr) := do
    let finalize : Unit → MetaM (Array Expr × Array BinderInfo × Expr) := fun _ => do
      let type := type.instantiateRevRange j mvars.size mvars
      return (mvars, bis, type)
    if maxMVars?.isEqSome mvars.size then
      finalize ()
    else
      match type with
      | .lam n d b bi =>
        let d     := d.instantiateRevRange j mvars.size mvars
        let mvar ← mkFreshExprMVar d kind n
        let mvars := mvars.push mvar
        let bis   := bis.push bi
        process mvars bis j b
      | _ => finalize ()

/-- A version of `Core.checkInterrupted` that does not crash. -/
def interrupted : CoreM Bool := do
  if ← IO.checkCanceled then return true
  if let some tk := (← read).cancelTk? then return ← tk.isSet
  else return false

def widthIndentColumnRange : TermElabM (Nat × Nat × Nat × Lsp.Range) := do
  let fileMap ← getFileMap
  let stxRange := (← getRef).getRange?.getD (panic! "No range found!")
  let range := fileMap.utf8RangeToLspRange stxRange
  let width := TryThis.getInputWidth (← getOptions)
  let (indent, column) := TryThis.getIndentAndColumn fileMap stxRange
  pure (width, indent, column, range)

/-- Replacements for certain `@[simp]` theorems with alternative encodings. -/
def SIMP_HARD_CODE : HashMap Name (Array Name) := .ofList [
  (`Nat.succ_eq_add_one, #[``Nat.succ.injEq]),
  (`Nat.add_zero, #[``Nat.add_zero, ``Nat.add_succ, ``Nat.succ_add, ``Nat.add_assoc]),
  (`Nat.mul_one, #[``Nat.mul_succ]),
  (`Nat.one_mul, #[``Nat.succ_mul, ``Nat.mul_assoc]),
  (`Nat.one_pow, #[``Nat.pow_succ, ``Nat.pow_add, ``Nat.mul_pow]),
  (`Nat.pow_one, #[])
]

/-- Retrieve the `Origin`s in `trie` consisting only of constants in `constSet`.  -/
partial def getOrigins (constSet : NameSet) (trie : Trie SimpTheorem) : Array Origin :=
  match trie with
  | node vs children =>
    let filtered := children.filter fun child =>
      match child.1 with
      | .proj name _ _ | .const name _ => constSet.contains name
      | .arrow => false
      | _ => true
    (vs.filterMap (fun x => if x.priority ≥ eval_prio default then some x.origin else none)) ++ filtered.flatMap (fun x => getOrigins constSet x.2)

/-- Obtain the `@[simp]` theorems that only use constants in `constSet` on the `lhs`. -/
def getRelevantSimpTheorems (constSet : NameSet) : MetaM (Array Name) := do
  let thms ← getSimpTheorems
  let tries ← constSet.toArray.filterMapM fun x => do
    -- TODO consider using something other than `typeArity1`.
    pure (thms.post.root.find? (.const x (← typeArity1 (← getConstInfo x).type)))
  let origins := tries.flatMap (getOrigins constSet)
  let names := origins.filterMap fun x =>
    if let .decl name _ _ := x then some name else none
  let relevant ← names.filterM fun x => do
    forallTelescopeReducing (← getConstInfo x).type fun xs body => do
      if !xs.all (fun x => body.containsFVar x.fvarId!) then pure false else
      if let some (typ, lhs, _) := (eq? body) then do
        if !typ.isSort then
          (lhs.getUsedConstantsAsSet.filter (!constSet.contains ·)).foldlM (fun acc name => do
            pure (acc && (← getUnfoldableConst? name).isSome)
          ) true
        else pure false
      else pure false
  pure (relevant.flatMap fun x => SIMP_HARD_CODE.getD x #[x])
